apiVersion: v1
kind: Namespace
metadata:
  name: odoo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-data
  namespace: odoo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: odoo
  namespace: odoo
  annotations:
    metallb.universe.tf/loadBalancerIPs: "172.18.1.229"
spec:
  type: LoadBalancer
  selector:
    app: odoo
  ports:
    - name: http
      port: 8069
      targetPort: 8069
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: odoo
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      securityContext:
        fsGroup: 101
        runAsUser: 101
        runAsGroup: 101
      initContainers:
        - name: init-db
          image: postgres:16-alpine
          command:
            - sh
            - -c
            - |
              PGPASSWORD='h$1f*@hc0M' psql -h postgres.databases.svc.cluster.local -U mikeb -d dataengineering -tc "SELECT 1 FROM pg_database WHERE datname = 'odoo'" | grep -q 1 || \
              PGPASSWORD='h$1f*@hc0M' psql -h postgres.databases.svc.cluster.local -U mikeb -d dataengineering -c "CREATE DATABASE odoo OWNER mikeb;"
      containers:
        - name: odoo
          image: odoo:19.0
          command:
            - odoo
            - --db_host=postgres.databases.svc.cluster.local
            - --db_port=5432
            - --db_user=mikeb
            - --db_password=h$1f*@hc0M
            - --database=odoo
            - --init=base
            - --without-demo=all
          ports:
            - name: http
              containerPort: 8069
          volumeMounts:
            - name: odoo-data
              mountPath: /var/lib/odoo
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          readinessProbe:
            tcpSocket:
              port: 8069
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8069
            initialDelaySeconds: 120
            periodSeconds: 30
      volumes:
        - name: odoo-data
          persistentVolumeClaim:
            claimName: odoo-data
