apiVersion: v1
kind: Namespace
metadata:
  name: odoo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-data
  namespace: odoo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
  namespace: odoo
data:
  odoo.conf: |
    [options]
    addons_path = /usr/lib/python3/dist-packages/odoo/addons
    data_dir = /var/lib/odoo
    admin_passwd = p@ssword12
    db_host = postgres.databases.svc.cluster.local
    db_port = 5432
    db_user = mikeb
    db_password = h$1f*@hc0M
    db_name = odoo
    http_port = 8069
    logfile = /var/log/odoo/odoo.log
    log_level = info
    workers = 2
    max_cron_threads = 1
---
apiVersion: v1
kind: Service
metadata:
  name: odoo
  namespace: odoo
  annotations:
    metallb.universe.tf/loadBalancerIPs: "172.18.1.229"
spec:
  type: LoadBalancer
  selector:
    app: odoo
  ports:
    - name: http
      port: 8069
      targetPort: 8069
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: odoo
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      initContainers:
        - name: init-db
          image: postgres:16-alpine
          command:
            - sh
            - -c
            - |
              PGPASSWORD='h$1f*@hc0M' psql -h postgres.databases.svc.cluster.local -U mikeb -d dataengineering -tc "SELECT 1 FROM pg_database WHERE datname = 'odoo'" | grep -q 1 || \
              PGPASSWORD='h$1f*@hc0M' psql -h postgres.databases.svc.cluster.local -U mikeb -d dataengineering -c "CREATE DATABASE odoo OWNER mikeb;"
      containers:
        - name: odoo
          image: odoo:19.0
          ports:
            - name: http
              containerPort: 8069
          env:
            - name: HOST
              value: "postgres.databases.svc.cluster.local"
            - name: PORT
              value: "5432"
            - name: USER
              value: "mikeb"
            - name: PASSWORD
              value: "h$1f*@hc0M"
          volumeMounts:
            - name: odoo-data
              mountPath: /var/lib/odoo
            - name: config
              mountPath: /etc/odoo
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /web/health
              port: 8069
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /web/health
              port: 8069
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: odoo-data
          persistentVolumeClaim:
            claimName: odoo-data
        - name: config
          configMap:
            name: odoo-config
