apiVersion: v1
kind: Namespace
metadata:
  name: minecraft-bedrock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-bedrock-data
  namespace: minecraft-bedrock
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-bedrock
  namespace: minecraft-bedrock
  annotations:
    metallb.universe.tf/loadBalancerIPs: "172.18.1.228"
spec:
  type: LoadBalancer
  selector:
    app: minecraft-bedrock
  ports:
    - name: bedrock
      port: 19133
      targetPort: 19132
      protocol: UDP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-bedrock
  namespace: minecraft-bedrock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-bedrock
  template:
    metadata:
      labels:
        app: minecraft-bedrock
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-bedrock-server:latest
        ports:
        - containerPort: 19132
          protocol: UDP
        env:
        - name: EULA
          value: "TRUE"
        - name: SERVER_NAME
          value: "Mike's Homelab Bedrock Server"
        - name: GAMEMODE
          value: "survival"
        - name: DIFFICULTY
          value: "normal"
        - name: LEVEL_SEED
          value: "8097496586259528417"
        - name: LEVEL_NAME
          value: "HomelabWorld"
        - name: MAX_PLAYERS
          value: "10"
        - name: ALLOW_CHEATS
          value: "false"
        - name: VIEW_DISTANCE
          value: "12"
        - name: TICK_DISTANCE
          value: "6"
        - name: MAX_THREADS
          value: "8"
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "2Gi"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minecraft-bedrock-data
