apiVersion: v1
kind: Namespace
metadata:
  name: minecraft-bedrock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-bedrock-data
  namespace: minecraft-bedrock
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-bedrock
  namespace: minecraft-bedrock
  annotations:
    metallb.universe.tf/loadBalancerIPs: "172.18.1.228"
spec:
  type: LoadBalancer
  selector:
    app: minecraft-bedrock
  ports:
    - name: bedrock
      port: 19133
      targetPort: 19132
      protocol: UDP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-bedrock
  namespace: minecraft-bedrock
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minecraft-bedrock
  template:
    metadata:
      labels:
        app: minecraft-bedrock
    spec:
      containers:
        - name: minecraft-bedrock
          image: itzg/minecraft-bedrock-server:latest
          ports:
            - name: bedrock
              containerPort: 19132
              protocol: UDP
          env:
            - name: EULA
              value: "TRUE"
            - name: SERVER_NAME
              value: "Mike's Homelab Bedrock Server"
            - name: GAMEMODE
              value: "survival"
            - name: DIFFICULTY
              value: "normal"
            - name: LEVEL_SEED
              value: "8097496586259528417"
            - name: MAX_PLAYERS
              value: "10"
            - name: ALLOW_CHEATS
              value: "false"
            - name: ONLINE_MODE
              value: "true"
            - name: WHITE_LIST
              value: "false"
            - name: VIEW_DISTANCE
              value: "32"
            - name: TICK_DISTANCE
              value: "4"
            - name: PLAYER_IDLE_TIMEOUT
              value: "30"
            - name: MAX_THREADS
              value: "8"
            - name: LEVEL_NAME
              value: "HomelabWorld"
            - name: LEVEL_TYPE
              value: "DEFAULT"
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minecraft-bedrock-data
