---
apiVersion: v1
kind: Namespace
metadata:
  name: homepage
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    title: Kubernetes Homelab
    background: https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=1920
    theme: dark
    color: slate
    headerStyle: boxed
    layout:
      Monitoring:
        style: row
        columns: 4
      Infrastructure:
        style: row
        columns: 4
      Applications:
        style: row
        columns: 3
  
  services.yaml: |
    - Monitoring:
        - Grafana:
            icon: grafana.png
            href: http://grafana.vgriz.com
            description: Metrics & Dashboards
        - Prometheus:
            icon: prometheus.png
            href: http://prom.vgriz.com
            description: Metrics Database
        - Alertmanager:
            icon: alertmanager.png
            href: http://alert.vgriz.com:9093
            description: Alert Management
        - Uptime Kuma:
            icon: uptime-kuma.png
            href: http://uptime.vgriz.com
            description: Service Monitoring
    
    - Infrastructure:
        - ArgoCD:
            icon: argocd.png
            href: http://argocd.vgriz.com
            description: GitOps Platform
        - MinIO:
            icon: minio.png
            href: http://minio.vgriz.com
            description: Object Storage
        - Ceph Dashboard:
            icon: ceph.png
            href: http://172.18.1.60:7000
            description: Storage Cluster
        - Velero:
            icon: backup.png
            href: "#"
            description: Backup Solution
    
    - Applications:
        - Jupyter Lab:
            icon: jupyter.png
            href: http://jupyter.vgriz.com
            description: Data Science Notebooks
  
  bookmarks.yaml: |
    - Documentation:
        - Kubernetes Docs:
            - icon: kubernetes.png
              href: https://kubernetes.io/docs/
        - Helm Charts:
            - icon: helm.png
              href: https://artifacthub.io/
  
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      serviceAccountName: homepage
      containers:
      - name: homepage
        image: ghcr.io/gethomepage/homepage:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: config
          mountPath: /app/config
      volumes:
      - name: config
        configMap:
          name: homepage-config
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage
  namespace: homepage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage
rules:
  - apiGroups: [""]
    resources: ["namespaces", "pods", "nodes"]
    verbs: ["get", "list"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homepage
subjects:
  - kind: ServiceAccount
    name: homepage
    namespace: homepage
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: homepage
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: homepage
