apiVersion: v1
kind: Service
metadata:
  name: nginx-hello-world
  namespace: nginx-hello-world
  labels:
    app.kubernetes.io/name: nginx-hello-world
    app.kubernetes.io/part-of: storyops-smoke-tests
  annotations:
    metallb.universe.tf/loadBalancerIPs: "172.18.1.212"
spec:
  type: LoadBalancer
  loadBalancerIP: 172.18.1.212
  selector:
    app.kubernetes.io/name: nginx-hello-world
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
