apiVersion: v1
kind: Service
metadata:
  name: gatus
  namespace: gatus
  annotations:
    metallb.universe.tf/loadBalancerIPs: "172.18.1.223"
spec:
  type: LoadBalancer
  selector:
    app: gatus
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatus
  namespace: gatus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatus
  template:
    metadata:
      labels:
        app: gatus
    spec:
      containers:
        - name: gatus
          image: twinproduction/gatus:v5.11.0
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: gatus-config
              mountPath: /config
            - name: gatus-data
              mountPath: /data
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: gatus-config
          configMap:
            name: gatus-config
        - name: gatus-data
          persistentVolumeClaim:
            claimName: gatus-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gatus-data
  namespace: gatus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 2Gi
