---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rook-ceph-mgr
  namespace: rook-ceph
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: rook-ceph-mgr
  endpoints:
    - port: http-metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rook-ceph-exporter
  namespace: rook-ceph
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: rook-ceph-exporter
  endpoints:
    - port: ceph-exporter-http-metrics
      interval: 30s
