apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kiali.org/helm-charts
    chart: kiali-server
    targetRevision: 2.2.0
    helm:
      valuesObject:
        auth:
          strategy: anonymous
        deployment:
          service_type: LoadBalancer
          ingress:
            enabled: false
        external_services:
          prometheus:
            url: http://kube-prometheus-stack-prometheus.monitoring:80
          grafana:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
