apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-home
  namespace: code-server
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: code-server
  namespace: code-server
  annotations:
    metallb.universe.tf/loadBalancerIPs: "172.18.1.218"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: code-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  namespace: code-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
        - name: code-server
          image: codercom/code-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: code-server-secret
                  key: password
            # Optionally pin a working directory:
            - name: DOCKER_USER
              value: "coder"
          volumeMounts:
            - name: home
              mountPath: /home/coder
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      volumes:
        - name: home
          persistentVolumeClaim:
            claimName: code-server-home
