apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-config
  namespace: code-server
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: code-server
  namespace: code-server
  annotations:
    metallb.universe.tf/loadBalancerIPs: "172.18.1.218"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8443
  selector:
    app: code-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  namespace: code-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
        - name: code-server
          image: lscr.io/linuxserver/code-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8443
              name: http
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Los_Angeles"
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: code-server-secret
                  key: password
            # Optional: default workspace inside /config
            - name: DEFAULT_WORKSPACE
              value: "/config/workspace"
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: code-server-config
