apiVersion: v1
kind: Secret
metadata:
  name: paperless-secret
  namespace: paperless-ngx
type: Opaque
stringData:
  admin-user: "admin"
  admin-password: "p@ssword12"
  secret-key: "change-me-to-a-random-string-of-at-least-50-characters"
