apiVersion: v1
kind: Service
metadata:
  name: wazuh.indexer
  namespace: wazuh
spec:
  clusterIP: None
  selector:
    app: wazuh-indexer
  ports:
    - name: http
      port: 9200
      targetPort: 9200
