apiVersion: v1
kind: Service
metadata:
  name: wazuh-manager
  namespace: wazuh
spec:
  type: ClusterIP
  selector:
    app: wazuh-manager
  ports:
    - name: registration
      port: 1514
      targetPort: 1514
      protocol: TCP
    - name: cluster
      port: 1516
      targetPort: 1516
      protocol: TCP
    - name: api
      port: 55000
      targetPort: 55000
      protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-manager
  namespace: wazuh
spec:
  serviceName: wazuh-manager
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-manager
  template:
    metadata:
      labels:
        app: wazuh-manager
    spec:
      containers:
        - name: wazuh-manager
          image: wazuh/wazuh-manager:4.8.0
          ports:
            - name: registration
              containerPort: 1514
            - name: cluster
              containerPort: 1516
            - name: api
              containerPort: 55000
          env:
            - name: INDEXER_URL
              value: "https://wazuh-indexer:9200"
            - name: INDEXER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wazuh-creds
                  key: username
            - name: INDEXER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wazuh-creds
                  key: password
            - name: FILEBEAT_SSL_VERIFICATION_MODE
              value: "none"
            - name: SSL_CERTIFICATE_AUTHORITIES
              value: ""
            - name: SSL_CERTIFICATE
              value: ""
            - name: SSL_KEY
              value: ""
            - name: API_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wazuh-creds
                  key: api-username
            - name: API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wazuh-creds
                  key: api-password
          volumeMounts:
            - name: wazuh-manager-data
              mountPath: /var/ossec/data
            - name: wazuh-manager-etc
              mountPath: /var/ossec/etc
            - name: wazuh-manager-logs
              mountPath: /var/ossec/logs
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
  volumeClaimTemplates:
    - metadata:
        name: wazuh-manager-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: rook-ceph-block
        resources:
          requests:
            storage: 20Gi
    - metadata:
        name: wazuh-manager-etc
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: rook-ceph-block
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: wazuh-manager-logs
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: rook-ceph-block
        resources:
          requests:
            storage: 10Gi
