apiVersion: v1
kind: Service
metadata:
  name: wazuh-indexer
  namespace: wazuh
spec:
  type: ClusterIP
  selector:
    app: wazuh-indexer
  ports:
    - name: http
      port: 9200
      targetPort: 9200
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-indexer
  namespace: wazuh
spec:
  serviceName: wazuh-indexer
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-indexer
  template:
    metadata:
      labels:
        app: wazuh-indexer
    spec:
      initContainers:
        - name: sysctl
          image: busybox
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
        - name: fix-permissions
          image: busybox
          command:
            - sh
            - -c
            - |
              chown -R 1000:1000 /var/lib/wazuh-indexer
              chmod -R 755 /var/lib/wazuh-indexer
          volumeMounts:
            - name: wazuh-indexer-data
              mountPath: /var/lib/wazuh-indexer
          securityContext:
            runAsUser: 0
      containers:
        - name: wazuh-indexer
          image: wazuh/wazuh-indexer:4.8.0
          ports:
            - name: http
              containerPort: 9200
          env:
            - name: OPENSEARCH_JAVA_OPTS
              value: "-Xms1g -Xmx1g"
            - name: bootstrap.memory_lock
              value: "true"
            - name: discovery.type
              value: "single-node"
            - name: network.host
              value: "0.0.0.0"
            - name: plugins.security.disabled
              value: "true"
          volumeMounts:
            - name: wazuh-indexer-data
              mountPath: /var/lib/wazuh-indexer
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          resources:
            requests:
              cpu: "500m"
              memory: "2Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
  volumeClaimTemplates:
    - metadata:
        name: wazuh-indexer-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: rook-ceph-block
        resources:
          requests:
            storage: 50Gi
