apiVersion: v1
kind: Service
metadata:
  name: bookstack
  namespace: bookstack
  annotations:
    metallb.universe.tf/loadBalancerIPs: "172.18.1.217"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: bookstack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstack
  namespace: bookstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstack
  template:
    metadata:
      labels:
        app: bookstack
    spec:
      containers:
        - name: bookstack
          image: lscr.io/linuxserver/bookstack:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Los_Angeles"
            - name: APP_URL
              value: "http://bookstack.vgriz.com"
            - name: DB_HOST
              value: "bookstack-mariadb.bookstack.svc.cluster.local"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: bookstack-db-secret
                  key: mariadb-user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: bookstack-db-secret
                  key: mariadb-password
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: bookstack-db-secret
                  key: mariadb-database
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: bookstack-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstack-config
  namespace: bookstack
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 10Gi
