apiVersion: v1
kind: Service
metadata:
  name: bookstack-mariadb
  namespace: bookstack
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  selector:
    app: bookstack-mariadb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bookstack-mariadb
  namespace: bookstack
spec:
  serviceName: bookstack-mariadb
  replicas: 1
  selector:
    matchLabels:
      app: bookstack-mariadb
  template:
    metadata:
      labels:
        app: bookstack-mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:11
          imagePullPolicy: IfNotPresent
          ports:
            - name: mysql
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bookstack-db-secret
                  key: mariadb-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: bookstack-db-secret
                  key: mariadb-database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: bookstack-db-secret
                  key: mariadb-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bookstack-db-secret
                  key: mariadb-password
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: rook-ceph-block
        resources:
          requests:
            storage: 10Gi
