apiVersion: v1
kind: Secret
metadata:
  name: bookstack-db-secret
  namespace: bookstack
type: Opaque
stringData:
  mariadb-root-password: "p@ssword12"
  mariadb-user: "bookstack"
  mariadb-password: "p@ssword12"
  mariadb-database: "bookstack"
