apiVersion: v1
kind: ConfigMap
metadata:
  name: crowdsec-dashboard-html
  namespace: crowdsec
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>CrowdSec Dashboard</title>
      <meta http-equiv="refresh" content="30">
      <style>
        body { font-family: Arial; margin: 20px; background: #1a1a1a; color: #fff; }
        .container { max-width: 1200px; margin: 0 auto; }
        .card { background: #2a2a2a; border-radius: 8px; padding: 20px; margin: 20px 0; }
        h1 { color: #00b4d8; }
        h2 { color: #0077b6; margin-top: 0; }
        pre { background: #000; padding: 15px; border-radius: 4px; overflow-x: auto; }
        .metric { display: inline-block; margin: 10px 20px 10px 0; }
        .metric-value { font-size: 32px; font-weight: bold; color: #00b4d8; }
        .metric-label { font-size: 14px; color: #aaa; }
        .alert { color: #ff6b6b; font-weight: bold; }
        .success { color: #51cf66; font-weight: bold; }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>🛡️ CrowdSec Security Dashboard</h1>
        
        <div class="card">
          <h2>Quick Stats</h2>
          <div class="metric">
            <div class="metric-value" id="total-bans">Loading...</div>
            <div class="metric-label">Total Bans</div>
          </div>
          <div class="metric">
            <div class="metric-value" id="active-decisions">0</div>
            <div class="metric-label">Active Decisions</div>
          </div>
          <div class="metric">
            <div class="metric-value" id="api-hits">Loading...</div>
            <div class="metric-label">API Requests</div>
          </div>
        </div>

        <div class="card">
          <h2>CrowdSec CLI Access</h2>
          <p>To interact with CrowdSec, use these commands:</p>
          <pre>kubectl exec -n crowdsec $(kubectl get pod -n crowdsec -o name) -- cscli metrics
kubectl exec -n crowdsec $(kubectl get pod -n crowdsec -o name) -- cscli decisions list
kubectl exec -n crowdsec $(kubectl get pod -n crowdsec -o name) -- cscli alerts list</pre>
        </div>

        <div class="card">
          <h2>Threat Intelligence</h2>
          <p class="success">✓ Connected to CrowdSec Community Blocklist</p>
          <p>Your instance is sharing threat intelligence with the CrowdSec network and receiving real-time updates about malicious IPs.</p>
          
          <h3>Current Threat Categories:</h3>
          <ul id="threat-list">
            <li>SSH Bruteforce: <span id="ssh-count">Loading...</span> IPs blocked</li>
            <li>HTTP Bruteforce: <span id="http-bf-count">Loading...</span> IPs blocked</li>
            <li>HTTP Crawlers: <span id="crawl-count">Loading...</span> IPs blocked</li>
            <li>HTTP DoS: <span id="dos-count">Loading...</span> IPs blocked</li>
            <li>HTTP Exploits: <span id="exploit-count">Loading...</span> IPs blocked</li>
            <li>HTTP Scanning: <span id="scan-count">Loading...</span> IPs blocked</li>
          </ul>
        </div>

        <div class="card">
          <h2>Links</h2>
          <ul>
            <li><a href="http://crowdsec.vgriz.com:8080" style="color: #00b4d8;">CrowdSec API</a> (API endpoint)</li>
            <li><a href="https://app.crowdsec.net" style="color: #00b4d8;">CrowdSec Cloud Console</a> (requires account)</li>
            <li><a href="http://metabase.vgriz.com" style="color: #00b4d8;">Metabase</a> (for custom dashboards)</li>
          </ul>
        </div>
      </div>

      <script>
        const metrics = {
          totalBans: 16103,
          sshBruteforce: 3898,
          httpBruteforce: 7965,
          httpCrawl: 298,
          httpDos: 82,
          httpExploit: 3073,
          httpScan: 787,
          apiHits: 1374
        };

        document.getElementById('total-bans').textContent = metrics.totalBans.toLocaleString();
        document.getElementById('active-decisions').textContent = '0';
        document.getElementById('api-hits').textContent = metrics.apiHits.toLocaleString();
        document.getElementById('ssh-count').textContent = metrics.sshBruteforce.toLocaleString();
        document.getElementById('http-bf-count').textContent = metrics.httpBruteforce.toLocaleString();
        document.getElementById('crawl-count').textContent = metrics.httpCrawl.toLocaleString();
        document.getElementById('dos-count').textContent = metrics.httpDos.toLocaleString();
        document.getElementById('exploit-count').textContent = metrics.httpExploit.toLocaleString();
        document.getElementById('scan-count').textContent = metrics.httpScan.toLocaleString();
      </script>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: crowdsec-dashboard
  namespace: crowdsec
  annotations:
    metallb.universe.tf/loadBalancerIPs: "172.18.1.227"
spec:
  type: LoadBalancer
  selector:
    app: crowdsec-dashboard
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crowdsec-dashboard
  namespace: crowdsec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crowdsec-dashboard
  template:
    metadata:
      labels:
        app: crowdsec-dashboard
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
          resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              cpu: "50m"
              memory: "64Mi"
      volumes:
        - name: html
          configMap:
            name: crowdsec-dashboard-html
