apiVersion: v1
kind: Service
metadata:
  name: crowdsec
  namespace: crowdsec
  annotations:
    metallb.universe.tf/loadBalancerIPs: "172.18.1.222"
spec:
  type: LoadBalancer
  selector:
    app: crowdsec
  ports:
    - name: api
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 6060
      targetPort: 6060
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crowdsec
  namespace: crowdsec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crowdsec
  template:
    metadata:
      labels:
        app: crowdsec
    spec:
      containers:
        - name: crowdsec
          image: crowdsecurity/crowdsec:v1.6.0
          ports:
            - name: api
              containerPort: 8080
            - name: metrics
              containerPort: 6060
          env:
            - name: COLLECTIONS
              value: "crowdsecurity/linux crowdsecurity/nginx"
            - name: GID
              value: "1000"
            - name: DISABLE_ONLINE_API
              value: "false"
          volumeMounts:
            - name: crowdsec-config
              mountPath: /etc/crowdsec/acquis.yaml
              subPath: acquis.yaml
            - name: crowdsec-db
              mountPath: /var/lib/crowdsec/data
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      volumes:
        - name: crowdsec-config
          configMap:
            name: crowdsec-config
        - name: crowdsec-db
          persistentVolumeClaim:
            claimName: crowdsec-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crowdsec-db
  namespace: crowdsec
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 5Gi
