apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patchmon
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/FlunkyMonkey/k8s-lab.git
    targetRevision: HEAD
    path: apps/patchmon
  destination:
    server: https://kubernetes.default.svc
    namespace: patchmon
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
