apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: robusta
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: robusta
  source:
    repoURL: https://github.com/FlunkyMonkey/k8s-lab.git
    targetRevision: main
    path: apps/robusta
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
