apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openvas
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/FlunkyMonkey/k8s-lab.git
    targetRevision: HEAD
    path: apps/openvas
  destination:
    server: https://kubernetes.default.svc
    namespace: openvas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
