apiVersion: v1
kind: Secret
metadata:
  name: n8n-postgres-credentials
  namespace: n8n
type: Opaque
stringData:
  POSTGRES_USER: n8n
  POSTGRES_PASSWORD: n8nP@ssw0rd!
  POSTGRES_DB: n8n
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-postgres-pvc
  namespace: n8n
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: n8n-postgres
  namespace: n8n
spec:
  serviceName: n8n-postgres
  replicas: 1
  selector:
    matchLabels:
      app: n8n-postgres
  template:
    metadata:
      labels:
        app: n8n-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: n8n-postgres-credentials
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
          subPath: pgdata
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: n8n-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: n8n-postgres
  namespace: n8n
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: n8n-postgres
