apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: databases
type: Opaque
stringData:
  POSTGRES_USER: mikeb
  POSTGRES_PASSWORD: h$1f*@hc0M
  POSTGRES_DB: dataengineering
