apiVersion: v1
kind: Service
metadata:
  name: wyoming-piper
  namespace: voice-services
spec:
  type: ClusterIP
  selector:
    app: wyoming-piper
  ports:
  - name: wyoming
    port: 10200
    targetPort: 10200
    protocol: TCP
