apiVersion: v1
kind: Service
metadata:
  name: wyoming-whisper
  namespace: voice-services
spec:
  type: ClusterIP
  selector:
    app: wyoming-whisper
  ports:
  - name: wyoming
    port: 10300
    targetPort: 10300
    protocol: TCP
