apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metabase-postgres-pvc
  namespace: metabase
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-block
---
apiVersion: v1
kind: Service
metadata:
  name: metabase-postgres
  namespace: metabase
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: metabase-postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: metabase-postgres
  namespace: metabase
spec:
  serviceName: metabase-postgres
  replicas: 1
  selector:
    matchLabels:
      app: metabase-postgres
  template:
    metadata:
      labels:
        app: metabase-postgres
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: postgres
          image: docker.io/library/postgres:15
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: metabase-db-secret
                  key: database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: metabase-db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: metabase-db-secret
                  key: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: metabase-postgres-pvc
